prerelease: true
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Type: Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: '🧰 Maintenance'
    labels:
      - 'Dependencies'
      - 'Type: Documentation'
      - 'Type: Infrastructure'
exclude-labels:
  - 'Type: Code Quality'
  - 'Type: Task'
  - 'Skip Changelog'
  - 'Dependencies'
change-template: '- $TITLE (#$NUMBER)'
template: |
  [View changes since last release](https://github.com/google/web-stories-wp/compare/$PREVIOUS_TAG...HEAD).

  ## Changes

  $CHANGES

  ## Contributors

  Code contributors to this release:

  $CONTRIBUTORS
