name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Type: Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: '🧰 Maintenance'
    labels:
      - 'Dependencies'
      - 'Type: Documentation'
      - 'Type: Infrastructure'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
