# Overall settings for PR integration via codecov.io
# See https://docs.codecov.io/docs/codecovyml-reference

codecov:
  notify:
    # Wait for: Karma (Editopr & Dashboard), Jest, PHPUnit
    after_n_builds: 4

# Separate PR statuses for project-level and patch-level coverage
# See https://docs.codecov.io/docs/commit-status
coverage:
  status:
    # Project-level coverage
    project:
      default:
        base: auto
        # Disable once code base is more mature.
        informational: true
        only_pulls: true
        target: auto
        threshold: 1%

      php:
        paths:
          - includes

      dashboard:
        paths:
          - assets/src/dashboard

      dashboard.unit:
        paths:
          - assets/src/dashboard
        flags:
          - unittests

      dashboard.karma:
        paths:
          - assets/src/dashboard
        flags:
          - karmatests

      editor:
        paths:
          - packages/story-editor/src

      editor.unit:
        paths:
          - packages/story-editor/src
        flags:
          - unittests

      editor.karma:
        paths:
          - packages/story-editor/src
        flags:
          - karmatests

    # Patch-level coverage (how well is the PR tested)
    patch:
      default:
        base: auto
        # Disable once code base is more mature.
        informational: true
        only_pulls: true
        target: auto
        threshold: 50%

# Pull request comments
# See https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: true
  branches:
    - 'main'

# See https://docs.codecov.io/docs/ignoring-paths
ignore:
  - bin/normalize-path.js
  - scoper.inc.php
  - web-stories.php
  - uninstall.php
  - includes/namespace.php
  - includes/compat
  - includes/polyfills
  - includes/templates
  - packages/migration/src/cli.js
  - assets/src/karma-fixture
  - packages/fonts/src/cli.js
  - includes/AMP/Integration/AMP_Story_Sanitizer.php
  - includes/REST_API/Stories_Settings_Controller.php
  - includes/REST_API/Stories_Users_Controller.php
