# Overall settings for PR integration via codecov.io
# See https://docs.codecov.io/docs/codecovyml-reference

# Separate PR statuses for project-level and patch-level coverage
# See https://docs.codecov.io/docs/commit-status
coverage:
  status:
    # Project-level coverage
    project:
      default:
        base: auto
        # Disable once code base is more mature.
        informational: true
        only_pulls: true
        target: auto
        threshold: 1%

      php:
        paths:
          - includes

      dashboard:
        paths:
          - packages/dashboard/src

      dashboard.unit:
        paths:
          - packages/dashboard/src
        flags:
          - unittests

      dashboard.karma:
        paths:
          - packages/dashboard/src
        flags:
          - karmatests

      editor:
        paths:
          - packages/story-editor/src

      editor.unit:
        paths:
          - packages/story-editor/src
        flags:
          - unittests

      editor.karma:
        paths:
          - packages/story-editor/src
        flags:
          - karmatests

    # Patch-level coverage (how well is the PR tested)
    patch:
      default:
        base: auto
        # Disable once code base is more mature.
        informational: true
        only_pulls: true
        target: auto
        threshold: 50%

# Pull request comments
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# See https://docs.codecov.io/docs/ignoring-paths
ignore:
  - bin
  - tests
  - .phpstorm.meta.php
  - scoper.inc.php
  - web-stories.php
  - uninstall.php
  - includes/namespace.php
  - includes/compat
  - includes/polyfills
  - includes/templates
  - includes/AMP/Integration/AMP_Story_Sanitizer.php
  - includes/REST_API/Stories_Settings_Controller.php
  - includes/REST_API/Stories_Users_Controller.php
  - packages/e2e-tests
  - packages/e2e-test-utils
  - packages/eslint-import-resolver
  - packages/fonts/scripts
  - packages/jest-amp
  - packages/jest-puppeteer-amp
  - packages/jest-resolver
  - packages/karma-failed-tests-reporter
  - packages/karma-fixture
  - packages/karma-puppeteer-client
  - packages/karma-puppeteer-launcher
  - packages/migration/scripts
  - packages/templates/scripts
  - packages/test-utils
  - '**/storybookUtils'
  - '**/testUtils'
