name: install-php-deps
description: Installs PHP dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709
      with:
        php-version: '8.0'
        coverage: none
        tools: composer, cs2pr

    - name: Install PHP dependencies
      uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6
      with:
        composer-options: '--prefer-dist --no-progress --no-interaction'
