version: '3.1'

services:
  wordpress:
    image: wordpress
    ports:
      - '127.0.0.1:8899:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'FS_METHOD', 'direct' );
        define( 'WEBSTORIES_DEV_MODE', true );
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../../:/var/www/html/wp-content/plugins/web-stories
      - ../../tests/e2e/plugins:/var/www/html/wp-content/plugins/web-stories-test-plugins
      - ../../tests/e2e/assets:/var/www/html/wp-content/e2e-assets
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/web-stories
      - ../../tests/e2e/assets:/var/www/html/wp-content/e2e-assets
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  wordpress_data:
