version: '3.1'

services:
  wordpress:
    image: wordpress:php${PHP_VERSION:-7.4}
    ports:
      - '127.0.0.1:8899:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
      WP_ENVIRONMENT_TYPE: local
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'FS_METHOD', 'direct' );
        define( 'WEBSTORIES_DEV_MODE', true );
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../../:/var/www/html/wp-content/plugins/web-stories
      - ../../packages/e2e-tests/src/plugins:/var/www/html/wp-content/plugins/web-stories-test-plugins
      - ../../packages/e2e-tests/src/assets:/var/www/html/wp-content/e2e-assets
    depends_on:
      - mysql

  cli:
    image: wordpress:cli-php${PHP_VERSION:-7.4}
    user: xfs
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/web-stories
      - ../../packages/e2e-tests/src/assets:/var/www/html/wp-content/e2e-assets
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mysql:
    image: mariadb:focal
    command: --max-allowed-packet=16777216
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  wordpress_data:
