/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// @todo Temporarily copied here to resolve dependencies. Move this file to some other package.

/**
 * External dependencies
 */
import { toUTCDate } from '@googleforcreators/date';

const formattedTemplatesArray = [
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 10,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID1',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        animations: [],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID1',
        pageTemplateType: 'cover',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '4e5d3a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'section',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID3',
        pageTemplateType: 'quote',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID4',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID4',
        pageTemplateType: 'editorial',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID5',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID5',
        pageTemplateType: 'list',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID6',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID6',
        pageTemplateType: 'table',
      },
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: 'ID7',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: 'ID7',
        pageTemplateType: 'steps',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-1.png',
        type: 'cover',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-2.png',
        type: 'section',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-3.png',
        type: 'quote',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-1.png',
        type: 'editorial',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-2.png',
        type: 'list',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-3.png',
        type: 'table',
      },
      {
        png: 'http://localhost:9876/__static__/featured-media-1.png',
        type: 'steps',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Cooking',
    slug: 'cooking',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 9,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'cover',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-2.png',
        type: 'cover',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'DIY',
    slug: 'diy',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 3,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'section',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-3.png',
        type: 'section',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Entertainment',
    slug: 'entertainment',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 4,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'editorial',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-1.png',
        type: 'editorial',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Fashion',
    slug: 'fashion',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 5,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'steps',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-2.png',
        type: 'steps',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Fitness',
    slug: 'fitness',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 6,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'cover',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-1.png',
        type: 'cover',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Travel',
    slug: 'travel',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 7,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'section',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-3.png',
        type: 'section',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    title: 'Wellbeing',
    slug: 'wellbeing',
  },
  {
    version: 2,
    createdBy: 'Google',
    description:
      'Maecenas ultrices tortor nibh, eu consequat magna maximus non. Quisque nec tellus lacus.',
    id: 8,
    isLocal: false,
    modified: toUTCDate('04-04-2020'),
    pages: [
      {
        elements: [
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundColor: {
              color: {
                r: 233,
                g: 213,
                b: 197,
              },
            },
            x: 1,
            y: 1,
            width: 1,
            height: 1,
            mask: {
              type: 'rectangle',
            },
            isBackground: true,
            isDefaultBackground: true,
            type: 'shape',
            id: 'ef056bde-fdc3-4f71-809a-e69c62ae914d',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            basedOn: '53004538-6bca-4ac6-810e-18bd81e84276',
            id: '51e3dfb3-fe95-4132-ade1-cd226982cf68',
            x: 65,
            y: 28,
            content:
              '<span style="color: #fff; letter-spacing: 0.09em">I</span>\n<span style="color: #fff; letter-spacing: 0.09em">WOKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">UP</span>\n<span style="color: #fff; letter-spacing: 0.09em">LIKE</span>\n<span style="color: #fff; letter-spacing: 0.09em">THIS</span>\n<span style="color: #fff; letter-spacing: 0.09em">”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Bungee Shade',
              service: 'fonts.google.com',
              fallbacks: ['cursive'],
              weights: [400],
              styles: ['regular'],
              variants: [[0, 400]],
            },
            fontSize: 84,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.1,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 56,
            y: 28,
            width: 330,
            height: 552,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '53004538-6bca-4ac6-810e-18bd81e84276',
            content:
              '<span style="color: rgba(40, 41, 43, 1)">I\nWOKE\nUP\nLIKE\nTHIS\n”</span>',
          },
          {
            opacity: 100,
            flip: {
              vertical: false,
              horizontal: false,
            },
            rotationAngle: 0,
            lockAspectRatio: true,
            backgroundTextMode: 'NONE',
            font: {
              family: 'Chivo',
              service: 'fonts.google.com',
              fallbacks: ['sans-serif'],
              weights: [300, 400, 700, 900],
              styles: ['italic', 'regular'],
              variants: [
                [0, 300],
                [0, 400],
                [0, 700],
                [0, 900],
                [1, 300],
                [1, 400],
                [1, 700],
                [1, 900],
              ],
            },
            fontSize: 40,
            backgroundColor: {
              color: {
                r: 196,
                g: 196,
                b: 196,
              },
            },
            lineHeight: 1.3,
            textAlign: 'center',
            padding: {
              vertical: 0,
              horizontal: 0,
              locked: true,
            },
            x: 110,
            y: 580,
            width: 202,
            height: 52,
            scale: 100,
            focalX: 50,
            focalY: 50,
            type: 'text',
            id: '96e93ceb-accb-4c38-b603-7d616174e5d3',
            content:
              '<span style="color: rgba(40, 41, 43, 1)"><span style="font-weight: 900">Beyoncé</span></span>',
          },
        ],
        backgroundOverlay: 'none',
        type: 'page',
        id: '65359a38-f1fa-4048-9b99-9415147b74d3',
        pageTemplateType: 'editorial',
      },
    ],
    postersByPage: [
      {
        png: 'http://localhost:9876/__static__/featured-media-2.png',
        type: 'editorial',
      },
    ],
    status: 'template',
    tags: ['Delicious', 'Baker', 'Cook'],
    colors: [
      { label: 'Pink', color: '#f3d9e1' },
      { label: 'Green', color: '#d8ddcc' },
      { label: 'Black', color: '#28292b' },
      { label: 'White', color: '#fff' },
      { label: 'Brown', color: '#eadfd6' },
    ],
    slug: 'beauty',
    title: 'Beauty',
  },
];

export default formattedTemplatesArray;
