name: Deploy QA artifacts

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  deploy-to-wiki:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download combined ZIP file
        uses: actions/download-artifact@v2
        with:
          name: All ZIP Files
          path: ${{ github.ref }}

      - name: Commit updates
        run: |
          git add .
          git status
          git commit -m "Build and publish ${{ github.ref }}"
          git pull --no-edit --quiet
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
