name: Plugin Check

on:
  push:
    paths:
      - '**.js'
      - '**.cjs'
      - '**.ts'
      - '**.tsx'
      - '**/package.json'
      - 'package-lock.json'
      - 'web-stories.php'
      - 'includes/**.php'
      - '.github/workflows/lint-plugin-check.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.js'
      - '**.cjs'
      - '**.ts'
      - '**.tsx'
      - '**/package.json'
      - 'package-lock.json'
      - 'web-stories.php'
      - 'includes/**.php'
      - '.github/workflows/lint-plugin-check.yml'

permissions:
  contents: read

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the (target) branch name.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: '8.0'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: |
          npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Install PHP dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          composer-options: '--prefer-dist --no-progress --no-interaction'

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version: latest

      - name: Build plugin
        run: bun run build:js

      - name: Bundle plugin
        run: bun run workflow:build-plugin

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './build/web-stories'
          exclude-directories: 'third-party'
          exclude-checks: |
            late_escaping
            plugin_readme
            plugin_review_phpcs
            plugin_updater
