# Handling skipped but required checks
# See https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
# Keep in sync with tests-e2e.yml

name: E2E Tests

on:
  push:
    # Only run for irrelevant changes.
    paths:
      - 'docs/**'
      - '.storybook/**'
      - '.wordpress-org/**'
      - '__mocks__/**'
      - '__static__/**'
      - 'tests/**'
      - '**.md'
      - '**.yml'
      - '**.neon.dist'
      - '**.xml.dist'
      - 'readme.txt'
      - '.editorconfig'
      - '.eslint*'
      - '.markdownlint*'
      - '.phpstorm.meta.php'
      - '.prettier*'
      - '.stylelint*'
      - '.github/workflows/**'
      - '!.github/workflows/tests-e2e.yml'
    branches:
      - main
      - release/*
  pull_request:
    # Only run for irrelevant changes.
    paths:
      - 'docs/**'
      - '.storybook/**'
      - '.wordpress-org/**'
      - '__mocks__/**'
      - '__static__/**'
      - 'tests/**'
      - '**.md'
      - '**.yml'
      - '**.neon.dist'
      - '**.xml.dist'
      - 'readme.txt'
      - '.editorconfig'
      - '.eslint*'
      - '.markdownlint*'
      - '.phpstorm.meta.php'
      - '.prettier*'
      - '.stylelint*'
      - '.github/workflows/**'
      - '!.github/workflows/tests-e2e.yml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the (target) branch name.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: '${{ matrix.browser }} - WP ${{ matrix.wp }} (${{ matrix.shard }})'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        # TODO: add back Firefox once support is more mature.
        browser: ['chrome']
        wp: ['5.7']
        snapshots: [false]
        # We want to split up the tests into 2 parts running in parallel.
        shard: ['1/2', '2/2']
        include:
          - browser: 'chrome'
            wp: 'latest'
            snapshots: true
            shard: '1/2'
          - browser: 'chrome'
            wp: 'latest'
            snapshots: true
            shard: '2/2'

    steps:
      - 24pxrun: 'echo "No build required"'
